import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 1 });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await page.goto('http://localhost:5173', { waitUntil: 'networkidle' });
await page.screenshot({ path: 'test-results/desktop.png', fullPage: true });
await page.getByRole('button', { name: 'Все клавиши управления', exact: true }).click();
await page.getByRole('heading', { name: 'Почувствуй свой корабль.' }).waitFor();
await page.keyboard.press('Escape');
await page.getByRole('button', { name: 'Открыть ангар', exact: false }).click();
assert.equal(await page.getByRole('button', { name: 'Пройди первую миссию', exact: false }).isDisabled(), true);
await page.getByRole('button', { name: 'Журнал полётов', exact: true }).click();
await page.getByRole('heading', { name: 'Здесь начнётся твоя история.' }).waitFor();
await page.getByRole('button', { name: 'Настройки', exact: true }).click();
await page.getByRole('switch', { name: 'Режим производительности' }).click();
assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('oui-low'))), true);
await page.getByRole('button', { name: 'Помощь и деплой', exact: false }).click();
await page.getByRole('button', { name: 'Через терминал' }).click();
await page.getByRole('heading', { name: 'Сохрани и отправь изменения' }).waitFor();
await page.getByRole('button', { name: 'Центр полётов', exact: true }).click();
await page.getByRole('button', { name: 'Начать полёт', exact: true }).click();
await page.waitForTimeout(5000);
assert.equal(await page.locator('.flight-canvas canvas').count(), 1);
await page.screenshot({ path: 'test-results/flight.png' });
const speed = Number(await page.locator('.speed>b').innerText());
assert.ok(speed > 20, 'flight should accelerate');
await page.keyboard.down('Shift');
await page.waitForTimeout(1500);
await page.keyboard.up('Shift');
assert.ok(Number(await page.locator('.speed>b').innerText()) > speed, 'boost should accelerate');
await page.keyboard.press('c');
await page.keyboard.press('Escape');
await page.getByRole('heading', { name: 'Космос подождёт.' }).waitFor();
const pausedDistance = await page.locator('.flight-progress b').innerText();
await page.waitForTimeout(500);
assert.equal(await page.locator('.flight-progress b').innerText(), pausedDistance);
await page.getByRole('button', { name: 'Продолжить полёт' }).click();
await page.getByRole('button', { name: 'Вернуться на станцию', exact: true }).click();
await page.setViewportSize({ width: 390, height: 844 });
await page.waitForTimeout(500);
await page.screenshot({ path: 'test-results/mobile.png', fullPage: true });
assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'no mobile overflow');
await page.getByRole('button', { name: 'Открыть меню' }).click();
await page.getByRole('button', { name: 'Помощь и деплой', exact: false }).click();
await page.getByRole('heading', { name: 'Твоя игра. На твоём GitHub.' }).waitFor();
assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'no guide overflow');
console.log(JSON.stringify({ result: 'PASS', speed, errors }, null, 2));
assert.equal(errors.length, 0);
await browser.close();
