import { useEffect, useState } from 'react';
import { ArrowUpRight, ArrowRight, Orbit, Rocket, Route, BookOpen, Settings2, ChevronRight, ChevronDown, Volume2, VolumeX, Bell, CircleHelp, Shield, Zap, LockKeyhole, Check, X, Copy, Download, ExternalLink, Keyboard, Radio, Crosshair, Clock3, Navigation, Menu, SlidersHorizontal, CheckCircle2, Monitor, Trophy } from 'lucide-react';
const Github = ({ size = 20 }: { size?: number }) => <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M9 19c-4.3 1.3-4.3-2.2-6-2.7m12 5v-3.9a3.4 3.4 0 0 0-1-2.6c3.3-.4 6.7-1.6 6.7-7.4a5.8 5.8 0 0 0-1.5-4 5.4 5.4 0 0 0-.1-3.9s-1.3-.4-4.2 1.5a14.1 14.1 0 0 0-7.6 0C4.4-.9 3.1-.5 3.1-.5A5.4 5.4 0 0 0 3 3.4a5.8 5.8 0 0 0-1.5 4c0 5.8 3.4 7 6.7 7.4A3.4 3.4 0 0 0 7.2 17v4.3" transform="translate(2 3) scale(.83)"/></svg>;
import Flight, { type FlightResult } from './Flight';
import './index.css';

type Page = 'station' | 'hangar' | 'missions' | 'journal' | 'guide' | 'settings';
type Modal = 'controls' | 'profile' | null;
const repository = 'https://github.com/alitojcubekov206-svg/oui';
const image = `${import.meta.env.BASE_URL}images/orbit.jpg`;
const navigation = [{ id: 'station', label: 'Центр полётов', icon: Orbit }, { id: 'hangar', label: 'Ангар', icon: Rocket }, { id: 'missions', label: 'Маршруты', icon: Route }, { id: 'journal', label: 'Журнал полётов', icon: BookOpen }] as const;
function load<T,>(key: string, initial: T): T { try { const value = localStorage.getItem(key); return value ? JSON.parse(value) : initial; } catch { return initial; } }
function Ship({ variant = false, className = '' }: { variant?: boolean; className?: string }) { return <svg className={`ship-art ${className}`} viewBox="0 0 380 180" fill="none" aria-label={variant ? 'Корабль Спектр' : 'Корабль Пионер'} role="img"><defs><linearGradient id={variant ? 'hull2' : 'hull'} x1="95" y1="30" x2="252" y2="150" gradientUnits="userSpaceOnUse"><stop stopColor={variant ? '#c5d1da' : '#9ba6b0'}/><stop offset=".46" stopColor="#465562"/><stop offset="1" stopColor="#171f28"/></linearGradient><filter id="engine"><feGaussianBlur stdDeviation="5"/></filter></defs><ellipse cx="201" cy="141" rx="130" ry="13" fill="#000" opacity=".2"/><path d="M104 121L49 126L145 65L179 73L297 84L330 99L217 105L144 142L121 132Z" fill={`url(#${variant ? 'hull2' : 'hull'})`} stroke="#83929d" strokeWidth=".7"/><path d="M143 93L104 121L123 133L172 106L261 96L294 84L201 86L166 63L145 65Z" fill="#293643"/><path d="M119 109L95 106L113 88L138 84L151 93L137 112Z" fill="#667580" stroke="#9ca7ae" strokeWidth=".7"/><path d="M183 113L157 115L170 96L197 93L212 101L202 117Z" fill="#667580" stroke="#9ca7ae" strokeWidth=".7"/><path d="M99 110L123 116L114 123L92 117Z" fill="#ff9953"/><path d="M165 115L190 121L179 130L155 123Z" fill="#ff9953"/><path d="M96 116L122 120L74 134L70 126Z" fill="#ff8140" opacity=".7" filter="url(#engine)"/><path d="M158 123L185 127L136 143L131 134Z" fill="#ff8140" opacity=".8" filter="url(#engine)"/><path d="M171 84L202 70L254 85L213 96Z" fill={`url(#${variant ? 'hull2' : 'hull'})`} stroke="#8c9aa3"/><path d="M201 77L222 80L238 85L214 88L193 83Z" fill="#101f2b" stroke="#5b7a91"/><path d="M74 115L130 81L138 84L92 115Z" fill="#d97846"/><path d="M239 102L292 96L305 99L247 106Z" fill="#d97846"/><path d="M153 73L165 65L174 75L163 88L154 85Z" fill="#aab4bb"/><path d="M141 127L178 110M263 91L284 91M116 92L134 94M181 101L198 104" stroke="#bcc7cc" strokeWidth="1" opacity=".6"/></svg>; }
function RouteMap({ large = false }: { large?: boolean }) { return <div className={`route-map ${large ? 'large' : ''}`}><svg viewBox="0 0 360 130" fill="none"><defs><pattern id="mapgrid" width="26" height="26" patternUnits="userSpaceOnUse"><path d="M26 0H0V26" stroke="#34404e" strokeWidth=".5"/></pattern></defs><rect width="360" height="130" fill="url(#mapgrid)"/><ellipse cx="227" cy="64" rx="81" ry="49" stroke="#536071" strokeDasharray="3 7" opacity=".5"/><circle cx="244" cy="59" r="28" fill="#293441" stroke="#4b5867"/><path d="M50 94L125 94L191 45L300 45" stroke="#f48c53" strokeWidth="1.5" strokeDasharray="4 4"/><circle cx="50" cy="94" r="5" fill="#f7985c"/><circle cx="50" cy="94" r="11" stroke="#f7985c" opacity=".3"/><path d="M299 39L305 45L299 51L293 45Z" fill="#f7985c"/><path d="M148 72L159 75L153 82Z" fill="#c2cbd3"/><circle cx="189" cy="89" r="3" fill="#56606e"/><circle cx="213" cy="23" r="4" fill="#56606e"/><circle cx="273" cy="101" r="5" fill="#56606e"/><circle cx="315" cy="73" r="3" fill="#56606e"/><text x="34" y="118" fill="#82909d" fontSize="8" fontFamily="monospace">СТАРТ</text><text x="278" y="27" fill="#82909d" fontSize="8" fontFamily="monospace">ГОРИЗОНТ</text></svg></div>; }
const controls = [{ keys: ['W', 'A', 'S', 'D'], title: 'Направление полёта', detail: 'W / S — вверх и вниз, A / D — влево и вправо. Можно использовать стрелки.' }, { keys: ['Q', 'E'], title: 'Крен корабля', detail: 'Наклон влево и вправо. Корабль плавно возвращается в исходное положение.' }, { keys: ['R', 'F'], title: 'Вертикальная тяга', detail: 'Альтернативное управление движением вверх и вниз.' }, { keys: ['SHIFT'], title: 'Форсаж', detail: 'Удерживай для ускорения. Энергия восстанавливается, когда форсаж выключен.' }, { keys: ['SPACE'], title: 'Экстренное уклонение', detail: 'Рывок по направлению движения или вправо. Перезарядка — 3 секунды.' }, { keys: ['X'], title: 'Торможение', detail: 'Удерживай, чтобы снизить скорость и пройти сложный участок.' }, { keys: ['C'], title: 'Сменить камеру', detail: 'Переключение между видом за кораблём и видом от первого лица.' }, { keys: ['ESC'], title: 'Пауза', detail: 'Остановить полёт, продолжить или вернуться на станцию.' }];

function CodeBlock({ children }: { children: string }) { const [copied, setCopied] = useState(false); const copy = async () => { try { await navigator.clipboard.writeText(children); setCopied(true); setTimeout(() => setCopied(false), 1800); } catch { setCopied(false); } }; return <div className="code-block"><pre>{children}</pre><button onClick={copy} aria-label="Скопировать команду">{copied ? <Check size={16}/> : <Copy size={16}/>}</button></div>; }
function DeployGuide() { const [method, setMethod] = useState<'desktop' | 'terminal'>('desktop'); return <div className="guide-layout"><div className="guide-content"><div className="notice"><Github size={22}/><div><b>От локального проекта до своей игры по ссылке</b><p>Код подготовлен к GitHub Pages. Публикацию нужно выполнить в своём аккаунте GitHub — из этой среды игра не опубликована.</p></div></div><div className="segmented"><button className={method === 'desktop' ? 'active' : ''} onClick={() => setMethod('desktop')}>Через GitHub Desktop</button><button className={method === 'terminal' ? 'active' : ''} onClick={() => setMethod('terminal')}>Через терминал</button></div>
      <section className="guide-step"><span className="step-number">01</span><div><h3>Скачай исходники и инструменты</h3><p>Скачай ZIP проекта и распакуй его: правой кнопкой по архиву → «Извлечь всё». Установи <a href="https://nodejs.org/" target="_blank" rel="noreferrer">Node.js LTS ↗</a> и {method === 'desktop' ? <a href="https://desktop.github.com/" target="_blank" rel="noreferrer">GitHub Desktop ↗</a> : <a href="https://git-scm.com/downloads" target="_blank" rel="noreferrer">Git ↗</a>}. Войди в свой аккаунт GitHub.</p><a className="secondary small" href={`${import.meta.env.BASE_URL}downloads/oui-source.zip`} download><Download size={16}/> Скачать исходники oui</a></div></section>
      {method === 'desktop' ? <><section className="guide-step"><span className="step-number">02</span><div><h3>Клонируй репозиторий</h3><p>В GitHub Desktop нажми <b>File → Clone repository</b> или <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>O</kbd>. Открой вкладку <b>URL</b>, вставь адрес ниже и нажми <b>Clone</b>.</p><CodeBlock>{repository + '.git'}</CodeBlock><p>Нажми <b>Repository → Show in Explorer</b> (<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>F</kbd>). Скопируй в эту папку содержимое распакованного проекта: выделить — <kbd>Ctrl + A</kbd>, копировать — <kbd>Ctrl + C</kbd>, вставить — <kbd>Ctrl + V</kbd>.</p><p>Важно: переноси файлы проекта, а не внешнюю ZIP-папку. В корне должны лежать <code>package.json</code>, <code>src</code>, <code>public</code> и <code>.github</code>. Не удаляй скрытую папку <code>.git</code> репозитория.</p></div></section><section className="guide-step"><span className="step-number">03</span><div><h3>Отправь код на GitHub</h3><p>Вернись в GitHub Desktop. Убедись, что выбрана ветка <b>main</b>. В поле <b>Summary</b> напиши «Launch oui», нажми <b>Commit to main</b>, затем <b>Push origin</b> (<kbd>Ctrl + P</kbd>). Если видишь <b>Publish branch</b>, нажми её.</p></div></section></> : <><section className="guide-step"><span className="step-number">02</span><div><h3>Клонируй проект и перенеси файлы</h3><p>Открой терминал в папке для проектов (в Windows: правая кнопка → «Открыть в Терминале»). Вставляй команды через <kbd>Ctrl + Shift + V</kbd>, запускай — <kbd>Enter</kbd>.</p><CodeBlock>{`git clone ${repository}.git\ncd oui`}</CodeBlock><p>Скопируй сюда содержимое распакованного архива, включая <code>.github</code>. Не заменяй папку <code>.git</code>.</p></div></section><section className="guide-step"><span className="step-number">03</span><div><h3>Сохрани и отправь изменения</h3><CodeBlock>{'git add .\ngit commit -m "Launch oui"\ngit branch -M main\ngit push -u origin main'}</CodeBlock><p>Если Git попросит имя и email, настрой <code>git config --global user.name "Твоё имя"</code> и <code>git config --global user.email "Твой email"</code>, затем повтори commit. Для push войди в GitHub в открывшемся окне — пароль аккаунта в терминал вводить не нужно.</p></div></section></>}
      <section className="guide-step"><span className="step-number">04</span><div><h3>Включи GitHub Pages</h3><p>Открой репозиторий → <b>Settings → Pages</b>. В разделе <b>Build and deployment</b> выбери <b>Source → GitHub Actions</b>. Для бесплатного GitHub аккаунта репозиторий должен быть публичным.</p><a className="text-link" href={`${repository}/settings/pages`} target="_blank" rel="noreferrer">Открыть настройки Pages <ArrowUpRight size={15}/></a></div></section>
      <section className="guide-step"><span className="step-number">05</span><div><h3>Запусти публикацию</h3><p>Открой вкладку <b>Actions → Deploy oui to Pages → Run workflow</b>, выбери <b>main</b> и нажми зелёную кнопку <b>Run workflow</b>. Подожди 1–3 минуты: оба задания должны стать зелёными.</p><p>Если workflow не появился, проверь, что на GitHub загружен файл <code>.github/workflows/deploy.yml</code>. Если предыдущий запуск упал до включения Pages, выбери <b>Re-run all jobs</b>.</p></div></section>
      <section className="guide-step last"><span className="step-number"><Check size={18}/></span><div><h3>Космос теперь по ссылке</h3><p>После успешного деплоя игра будет доступна по адресу ниже. Последующие push в main публикуются автоматически. Если видишь старую версию, нажми <kbd>Ctrl + F5</kbd>.</p><a className="published-link" href="https://alitojcubekov206-svg.github.io/oui/" target="_blank" rel="noreferrer">alitojcubekov206-svg.github.io/oui/ <ExternalLink size={16}/></a></div></section>
    </div><aside className="guide-aside panel"><span className="eyebrow">ШПАРГАЛКА ПИЛОТА</span><h3>Нужные клавиши</h3>{[['Ctrl + C', 'Копировать'], ['Ctrl + V', 'Вставить'], ['Ctrl + A', 'Выделить всё'], ['Ctrl + Shift + V', 'Вставить в терминал'], ['Enter', 'Выполнить команду'], ['Ctrl + P', 'Push в GitHub Desktop'], ['Ctrl + F5', 'Обновить без кэша']].map(([key, label]) => <div className="shortcut-line" key={key}><kbd>{key}</kbd><span>{label}</span></div>)}<div className="aside-note"><CircleHelp size={18}/><p>На macOS вместо Ctrl обычно используется ⌘ Command. Сочетания терминала могут отличаться.</p></div><h4>Проверка перед стартом</h4><p className="muted">В папке проекта выполни:</p><CodeBlock>{'npm install\nnpm run dev'}</CodeBlock><p className="muted">Открой адрес из терминала. Остановить локальный сервер — Ctrl + C.</p></aside></div>; }

export default function App() {
  const [page, setPage] = useState<Page>('station');
  const [modal, setModal] = useState<Modal>(null);
  const [playing, setPlaying] = useState(false);
  const [sound, setSound] = useState(() => load('oui-sound', false));
  const [lowGraphics, setLowGraphics] = useState(() => load('oui-low', false));
  const [pilot, setPilot] = useState(() => load('oui-pilot', 'Пилот'));
  const [draftName, setDraftName] = useState(pilot);
  const [flights, setFlights] = useState<FlightResult[]>(() => load('oui-flights', []));
  const [ship, setShip] = useState(() => load('oui-ship', 'Пионер'));
  const [notifications, setNotifications] = useState(false);
  const [mobileNav, setMobileNav] = useState(false);
  const [toast, setToast] = useState('');
  const unlocked = flights.some(f => f.success);
  const totalDistance = flights.reduce((total, flight) => total + flight.distance, 0);
  useEffect(() => { try { localStorage.setItem('oui-sound', JSON.stringify(sound)); localStorage.setItem('oui-low', JSON.stringify(lowGraphics)); localStorage.setItem('oui-pilot', JSON.stringify(pilot)); localStorage.setItem('oui-flights', JSON.stringify(flights)); localStorage.setItem('oui-ship', JSON.stringify(ship)); } catch {} }, [sound, lowGraphics, pilot, flights, ship]);
  useEffect(() => { if (toast) { const timer = setTimeout(() => setToast(''), 3500); return () => clearTimeout(timer); } }, [toast]);
  useEffect(() => { const key = (event: KeyboardEvent) => { if (event.key === 'Escape' && !playing) { setModal(null); setNotifications(false); setMobileNav(false); } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key); }, [playing]);
  useEffect(() => { if (!modal) return; const previous = document.activeElement as HTMLElement | null; const timer = setTimeout(() => document.querySelector<HTMLButtonElement>('.modal .close-button')?.focus(), 0); const trap = (e: KeyboardEvent) => { if (e.key !== 'Tab') return; const all = Array.from(document.querySelectorAll<HTMLElement>('.modal button, .modal input, .modal a')); const first = all[0], last = all[all.length - 1]; if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last?.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first?.focus(); } }; document.addEventListener('keydown', trap); return () => { clearTimeout(timer); document.removeEventListener('keydown', trap); previous?.focus(); }; }, [modal]);
  const navigate = (next: Page) => { setPage(next); setMobileNav(false); setNotifications(false); window.scrollTo(0, 0); };
  const titles: Record<Page, [string, string, string]> = { station: ['ТВОЯ СЛЕДУЮЩАЯ ОРБИТА', `Готов к вылету, ${pilot.toLowerCase()}?`, 'Корабль заправлен. Маршрут проложен. Осталось сделать первый шаг.'], hangar: ['ТЕХНИЧЕСКИЙ СЕКТОР', 'Твой корабль. Твои правила.', 'Выбирай свой характер полёта. Новые горизонты открывают новые возможности.'], missions: ['НАВИГАЦИЯ', 'У каждого пути есть начало.', 'Проложи маршрут через астероидный пояс и доберись до станции.'], journal: ['ТЕЛЕМЕТРИЯ', 'Каждый полёт — история.', 'Твои маршруты, результаты и маленькие победы. Всё сохраняется на этом устройстве.'], guide: ['ЦЕНТР ПОМОЩИ', 'Твоя игра. На твоём GitHub.', 'Подробная инструкция публикации oui — от первого клика до работающей ссылки.'], settings: ['БОРТОВОЙ КОМПЬЮТЕР', 'Настрой свой космос.', 'Параметры сохраняются автоматически на этом устройстве.'] };
  return <div className="app-shell">
    {mobileNav && <div className="sidebar-scrim" onClick={() => setMobileNav(false)}/>}
    <aside className={`sidebar ${mobileNav ? 'mobile-open' : ''}`}><a className="logo" href="#" onClick={e => { e.preventDefault(); navigate('station'); }}>oui<span className="logo-star">✳</span><span className="logo-caption">BEYOND THE ORDINARY</span></a><div className="nav-label">ПОЛЁТНАЯ СТАНЦИЯ</div><nav>{navigation.map(item => <button className={`nav-item ${page === item.id ? 'active' : ''}`} key={item.id} onClick={() => navigate(item.id)}><item.icon size={19} strokeWidth={1.65}/><span>{item.label}</span>{item.id === 'hangar' && <span className="nav-count">0{unlocked ? 2 : 1}</span>}{page === item.id && <span className="active-dot"/>}</button>)}</nav><div className="nav-divider"/><nav><button className={`nav-item ${page === 'settings' ? 'active' : ''}`} onClick={() => navigate('settings')}><Settings2 size={19} strokeWidth={1.65}/><span>Настройки</span></button><button className={`nav-item ${page === 'guide' ? 'active' : ''}`} onClick={() => navigate('guide')}><CircleHelp size={19} strokeWidth={1.65}/><span>Помощь и деплой</span><ArrowUpRight size={14}/></button></nav><div className="sidebar-bottom"><div className="station-card"><div className="orbital-icon"><Orbit size={28} strokeWidth={1}/><span/></div><h4>Большой космос.<br/>Твой первый шаг.</h4><p>Исследуй. Ошибайся.<br/>Лети дальше.</p><span className="build-tag"><i/> WEBGL · EARLY ACCESS</span></div><a className="github-link" href={repository} target="_blank" rel="noreferrer"><Github size={17}/><span>Проект на GitHub</span><ArrowUpRight size={14}/></a><div className="version"><span>oui © 2026</span><span>v0.1.0 alpha</span></div></div></aside>
    <div className="workspace"><header className="topbar"><div className="breadcrumbs"><button className="mobile-menu icon-button" aria-label="Открыть меню" onClick={() => setMobileNav(!mobileNav)}><Menu size={20}/></button><span>СТАНЦИЯ</span><ChevronRight size={13}/><b>{page === 'station' ? 'ЦЕНТР ПОЛЁТОВ' : page === 'guide' ? 'ПОМОЩЬ И ДЕПЛОЙ' : page === 'settings' ? 'НАСТРОЙКИ' : navigation.find(n => n.id === page)?.label.toUpperCase()}</b></div><div className="top-actions"><span className="system-online"><i/> Все системы в норме</span><button className={`icon-button audio-button ${sound ? 'enabled' : ''}`} onClick={() => setSound(!sound)} aria-label={sound ? 'Выключить звук' : 'Включить звук'} title={sound ? 'Звук включён' : 'Звук выключен'}>{sound ? <Volume2 size={18}/> : <VolumeX size={18}/>}</button><div className="notification-wrapper"><button className="icon-button notification-button" onClick={() => setNotifications(!notifications)} aria-label="Уведомления"><Bell size={18}/><i/></button>{notifications && <div className="notification-popover"><h4>Бортовые сообщения</h4><div><Radio size={19}/><p><b>Станция на связи</b><span>«Пионер» готов к первому вылету. Пройди маршрут, чтобы открыть «Спектр».</span></p></div><button className="text-link" onClick={() => navigate('missions')}>Посмотреть маршрут <ArrowRight size={15}/></button></div>}</div><span className="top-separator"/><button className="profile-button" onClick={() => { setDraftName(pilot); setModal('profile'); }}><span className="avatar"><Crosshair size={20}/></span><span>{pilot}<small>{unlocked ? 'Исследователь' : 'Кадет · Уровень 1'}</small></span><ChevronDown size={14}/></button></div></header>
    <main><div className="page-heading"><div><span className="eyebrow">{titles[page][0]}</span><h1>{titles[page][1]}</h1><p>{titles[page][2]}</p></div><div className="local-badge"><span/> Локальная станция<small>ПРОГРЕСС СОХРАНЯЕТСЯ</small></div></div>
    {page === 'station' && <>
      <section className="hero" style={{ backgroundImage: `url(${image})` }}><div className="hero-shade"/><div className="hero-grid"/><div className="hero-content"><span className="mission-label"><span/> МИССИЯ 01 <i/> ПОЯС КЕПЛЕРА</span><h2>За пределами<br/>привычного<span>.</span></h2><p>Только ты, твой корабль и бескрайний космос.<br/>Пройди сквозь астероиды. Найди свой путь.</p><div className="hero-buttons"><button className="primary" onClick={() => setPlaying(true)}><Rocket size={18}/> Начать полёт <ArrowUpRight size={20}/></button><button className="hero-control" onClick={() => setModal('controls')}><Keyboard size={18}/><span>Управление</span></button></div><div className="hero-note"><span className="key-tiny">↵</span> Твой первый полёт начинается здесь</div></div><div className="sector-badge"><span className="sector-cross">+</span><span>СЕКТОР 07 — КЕПЛЕР<small>28.4° N / 106.8° E</small></span></div><div className="ship-callout"><div className="callout-line"/><span>{ship.toUpperCase()}<small>РАЗВЕДЫВАТЕЛЬНЫЙ КЛАСС</small></span><span className="callout-plus">+</span></div><div className="hero-bottom"><div><span><Route size={15}/> ДИСТАНЦИЯ</span><b>5,5 <small>км</small></b></div><div><span><SlidersHorizontal size={15}/> СЛОЖНОСТЬ</span><b>Первый полёт <i className="difficulty-dots"><i/><i/><i/></i></b></div><div><span><Trophy size={15}/> НАГРАДА</span><b>Корабль «Спектр» <LockKeyhole size={13}/></b></div><span className="hero-ready"><i/> ГОТОВ К ЗАПУСКУ</span></div></section>
      <div className="section-heading"><h2>Подготовка к полёту <span>01 — 03</span></h2><span>Проверь детали. И вперёд.</span></div>
      <div className="preflight-grid"><section className="panel route-card"><div className="card-heading"><span><Route size={16}/> ТВОЙ МАРШРУТ</span><span className="mini-tag">01</span></div><div className="card-title-row"><h3>Пояс Кеплера</h3><span className="easy-badge">Начальный</span></div><p>От станции «Рассвет» до «Горизонта»</p><RouteMap/><button className="card-footer" onClick={() => navigate('missions')}><span>Астероиды · Планета · Свободный полёт</span><ArrowUpRight size={17}/></button></section>
      <section className="panel ship-card"><div className="card-heading"><span><Rocket size={16}/> ТВОЙ КОРАБЛЬ</span><span className="selected-indicator"><i/> ВЫБРАН</span></div><div className="card-title-row"><h3>{ship}</h3><span className="ship-type">MK–0{ship === 'Спектр' ? 2 : 1}</span></div><p>{ship === 'Спектр' ? 'Быстрее. Легче. Дальше.' : 'Надёжный. Манёвренный. Твой.'}</p><Ship variant={ship === 'Спектр'}/><div className="mini-ship-stats"><span><Zap size={12}/>{ship === 'Спектр' ? '73' : '62'} м/с</span><span><Shield size={12}/>100 щит</span></div><button className="card-footer" onClick={() => navigate('hangar')}><span>Открыть ангар <span className="footer-count">{unlocked ? 2 : 1} / 2 корабля</span></span><ArrowUpRight size={17}/></button></section>
      <section className="panel controls-card"><div className="card-heading"><span><Keyboard size={17}/> БЫСТРЫЙ ИНСТРУКТАЖ</span><span className="mini-tag">PC</span></div><h3>Всё под контролем</h3><div className="quick-control"><span><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd></span><span>Движение</span></div><div className="quick-control"><span><kbd className="wide-key">SHIFT</kbd></span><span>Форсаж <Zap size={12}/></span></div><div className="quick-control"><span><kbd className="wide-key">SPACE</kbd></span><span>Уклонение</span></div><div className="quick-control"><span><kbd>C</kbd></span><span>Сменить камеру</span></div><button className="card-footer" onClick={() => setModal('controls')}><span>Все клавиши управления</span><ArrowUpRight size={17}/></button></section></div>
      <div className="bottom-note"><span><Radio size={15}/><b>СОВЕТ СТАНЦИИ</b><span>Не спеши с форсажем. Иногда лучший манёвр — немного сбросить скорость.</span></span><span className="note-page">01 / 03</span></div>
    </>}
    {page === 'hangar' && <><div className="section-heading"><h2>Твой флот <span>0{unlocked ? 2 : 1} / 02</span></h2><span>Выбери корабль для следующего вылета</span></div><div className="hangar-grid">{['Пионер', 'Спектр'].map((name, i) => <section className={`panel hangar-ship ${ship === name ? 'is-selected' : ''}`} key={name}><div className="card-heading"><span>РАЗВЕДЧИК / MK–0{i + 1}</span>{i === 1 && !unlocked ? <LockKeyhole size={17}/> : <span className="selected-indicator"><i/>{ship === name ? 'ВЫБРАН' : 'ДОСТУПЕН'}</span>}</div><Ship variant={i === 1}/><h2>{name}</h2><p>{i === 0 ? 'Твой первый спутник в большом космосе. Сбалансированная тяга и предсказуемый характер.' : 'Следующая ступень. Облегчённый корпус и увеличенная крейсерская скорость для опытного пилота.'}</p><div className="ship-specs">{[['Скорость', i ? 90 : 70, i ? '73 м/с' : '62 м/с'], ['Манёвренность', 75, '75 / 100'], ['Щит', 100, '100 ед.'], ['Форсаж', 100, '125 м/с']].map(([label, value, text]) => <div key={label}><span>{label}<b>{text}</b></span><div className="meter"><i style={{ width: `${value}%` }}/></div></div>)}</div><button className={ship === name ? 'secondary' : 'primary'} disabled={i === 1 && !unlocked} onClick={() => { setShip(name); setToast(`Корабль «${name}» выбран`); }}>{i === 1 && !unlocked ? <><LockKeyhole size={16}/> Пройди первую миссию</> : ship === name ? <><Check size={17}/> Корабль выбран</> : <>Выбрать корабль <ArrowRight size={17}/></>}</button></section>)}</div><div className="inline-cta"><p>Корабль готов. Время проверить его в деле.</p><button className="primary" onClick={() => setPlaying(true)}>Начать полёт <ArrowUpRight size={18}/></button></div></>}
    {page === 'missions' && <section className="panel mission-detail"><div className="mission-visual" style={{backgroundImage: `url(${image})`}}><span className="mission-label">МИССИЯ 01 · ПОЯС КЕПЛЕРА</span><h2>Между камнем<br/>и бесконечностью.</h2></div><div className="mission-details"><div><span className="easy-badge">Начальный уровень</span><h2>Пояс Кеплера</h2><p>Пройди 5,5 км через движущееся астероидное поле. На середине маршрута гравитация планеты будет тянуть корабль вправо — компенсируй отклонение. Доберись до станции «Горизонт», сохранив щит.</p><div className="mission-facts"><span><Route size={17}/> 5,5 км</span><span><Clock3 size={17}/> ~ 90 секунд</span><span><Trophy size={17}/> «Спектр»</span></div><button className="primary" onClick={() => setPlaying(true)}><Rocket size={18}/> Отправиться в полёт <ArrowUpRight size={18}/></button></div><RouteMap large/></div><div className="mission-tip"><Shield size={18}/><p>Малые столкновения снимают 22 единицы щита, крупные — 45. После 8 секунд без урона щит начинает восстанавливаться. При разрушении можно начать заново.</p></div></section>}
    {page === 'journal' && <><div className="journal-stats">{[[Navigation, 'Общая дистанция', `${(totalDistance / 1000).toFixed(1)} км`], [Rocket, 'Всего вылетов', `${flights.length}`], [Trophy, 'Успешные миссии', `${flights.filter(f => f.success).length}`]].map(([Icon, label, value], index) => { const Component = Icon as typeof Rocket; return <div className="panel" key={index}><Component size={21}/><span>{label as string}</span><b>{value as string}</b></div>; })}</div><section className="panel journal-panel"><div className="card-heading"><span>ИСТОРИЯ ПОЛЁТОВ</span><span>НА ЭТОМ УСТРОЙСТВЕ</span></div>{flights.length ? <div className="table-scroll"><table><thead><tr><th>Дата</th><th>Корабль</th><th>Дистанция</th><th>Время</th><th>Результат</th></tr></thead><tbody>{[...flights].reverse().map(f => <tr key={f.id}><td>{new Date(f.date).toLocaleDateString('ru-RU')} <small>{new Date(f.date).toLocaleTimeString('ru-RU', {hour: '2-digit', minute: '2-digit'})}</small></td><td>{f.ship}</td><td>{(f.distance / 1000).toFixed(2)} км</td><td>{f.time} сек</td><td><span className={f.success ? 'easy-badge' : 'failure-badge'}>{f.success ? 'Завершён' : 'Корабль потерян'}</span></td></tr>)}</tbody></table></div> : <div className="empty-state"><div className="empty-orbit"><Orbit size={45} strokeWidth={1}/></div><h2>Здесь начнётся твоя история.</h2><p>Пока ни одного завершённого полёта.<br/>Первый маршрут уже ждёт тебя.</p><button className="primary" onClick={() => setPlaying(true)}><Rocket size={17}/> Начать первый полёт</button></div>}</section></>}
    {page === 'guide' && <DeployGuide/>}
    {page === 'settings' && <div className="settings-layout"><section className="panel settings-panel"><div className="card-heading"><span><Settings2 size={17}/> ПАРАМЕТРЫ ПОЛЁТА</span><CheckCircle2 size={17}/></div><div className="setting-row"><div><Volume2 size={21}/><span><b>Звук двигателя</b><small>Синтезированный звук тяги и форсажа во время полёта</small></span></div><button role="switch" aria-checked={sound} aria-label="Звук двигателя" className={`toggle ${sound ? 'on' : ''}`} onClick={() => setSound(!sound)}><i/></button></div><div className="setting-row"><div><Monitor size={21}/><span><b>Режим производительности</b><small>Меньше астероидов и ниже разрешение для слабых устройств</small></span></div><button role="switch" aria-checked={lowGraphics} aria-label="Режим производительности" className={`toggle ${lowGraphics ? 'on' : ''}`} onClick={() => setLowGraphics(!lowGraphics)}><i/></button></div><div className="setting-row"><div><Keyboard size={21}/><span><b>Управление</b><small>Клавиатура на ПК, экранные кнопки на телефоне</small></span></div><button className="secondary small" onClick={() => setModal('controls')}>Все клавиши <ArrowUpRight size={15}/></button></div><div className="setting-row"><div><Crosshair size={21}/><span><b>Позывной пилота</b><small>{pilot}</small></span></div><button className="secondary small" onClick={() => { setDraftName(pilot); setModal('profile'); }}>Изменить</button></div></section><section className="panel about-panel"><Orbit size={32} strokeWidth={1}/><h3>oui / early access</h3><p>Браузерный 3D-прототип на React и Three.js. Один маршрут, два корабля и бесконечно много попыток.</p><p>Это WebGL-игра, не сборка Unreal Engine для Windows. Прогресс хранится локально и не синхронизируется между устройствами.</p><button className="text-link" onClick={() => navigate('guide')}>Как опубликовать игру <ArrowUpRight size={16}/></button></section></div>}
    <footer className="main-footer"><span><span className="footer-logo">oui</span> Космос ближе, чем кажется.</span><span><i/> СДЕЛАНО ДЛЯ ТЕХ, КТО СМОТРИТ ВВЕРХ <span className="footer-star">✳</span></span></footer>
    </main></div>
    {modal && <div className="modal-backdrop" onClick={() => setModal(null)}><section className={`modal ${modal === 'profile' ? 'profile-modal' : ''}`} role="dialog" aria-modal="true" aria-labelledby="modal-title" onClick={e => e.stopPropagation()}><button className="icon-button close-button" aria-label="Закрыть" onClick={() => setModal(null)}><X size={20}/></button><span className="eyebrow">{modal === 'controls' ? 'ЛЁТНАЯ ИНСТРУКЦИЯ' : 'ЛИЧНОЕ ДЕЛО'}</span><h2 id="modal-title">{modal === 'controls' ? 'Почувствуй свой корабль.' : 'Как тебя называть, пилот?'}</h2>{modal === 'controls' ? <><p>Переключи раскладку на английскую. Нажимай плавно — корабль движется с инерцией.</p><div className="full-controls">{controls.map(control => <div className="full-control" key={control.title}><div>{control.keys.map(key => <kbd key={key}>{key}</kbd>)}</div><span><b>{control.title}</b><small>{control.detail}</small></span></div>)}</div><div className="modal-footer"><span><Monitor size={16}/> На телефоне используй экранные кнопки</span><button className="primary small" onClick={() => setModal(null)}>Всё понятно <Check size={16}/></button></div></> : <form onSubmit={e => { e.preventDefault(); setPilot(draftName.trim() || 'Пилот'); setModal(null); setToast('Позывной обновлён'); }}><p>Твой позывной будет отображаться на станции.</p><label htmlFor="pilot-name">ПОЗЫВНОЙ</label><input id="pilot-name" value={draftName} maxLength={20} onChange={e => setDraftName(e.target.value)} placeholder="Пилот" autoComplete="off" required/><button className="primary" type="submit">Сохранить <Check size={17}/></button></form>}</section></div>}
    {playing && <Flight ship={ship} lowGraphics={lowGraphics} sound={sound} onExit={() => setPlaying(false)} onFinish={result => setFlights(current => [...current, result])}/>}
    {toast && <div className="toast" role="status"><CheckCircle2 size={18}/>{toast}</div>}
  </div>;
}
